name: Clayton Moser
favicon: null
layout_spectrum: 1
typography_spectrum: 0.21828
title: Professional Site
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.624351117759943
  lightness: 0.4375
  saturation: 0.75
  rhythmicContrast: 1
purpose: []
